development:
  adapter: postgresql
  host: http://137.184.183.119/
  port: 5432                            # Vm Port  
  database: root             # Database Name  
  username: root                   # User Name  

 
