development:
  adapter: postgresql
  host: 137.184.183.119
  port: 5432                            # Vm Port  
  database: root             # Database Name  
  username: root   
  password: kaneida29                # User Name  

 